# Generated by Django 3.1.7 on 2021-03-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='blog_image', upload_to='blog_image', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
